/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main()
{
    int sum = 0;
    int currentTerm = 2;
    int secondLastTerm = 1;
    int previousLastTerm = 1;

    while (currentTerm < 4000000)
    {
        currentTerm = secondLastTerm + previousLastTerm;
        secondLastTerm = previousLastTerm;
        previousLastTerm = currentTerm;

        if (currentTerm % 2 == 0)
        {
            sum += currentTerm;
        }
    }

    cout << "The sum of the even-valued Fibonacci terms whose values do not exceed four million is " << sum << "." << endl;
    return 0;
}
